# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
    inputs:
      branch:
        type: string
        description: Enter a branch 
        default: main


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4 
      with: 
        ref: ${{ inputs.branch }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore .\HelloWorld\HelloWorld.csproj
    - name: Build
      run: py build.py "${ inputs.branch }"

    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
